# This is a basic workflow to help you get started with Actions
name: Create Release on Push

on:
  push:
      
  workflow_dispatch:
   inputs:
      draft-release:
        type: boolean
        default: true
        description: Whether to publish the release as a draft.

permissions:
  packages: write
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Zip Project Files
      run: |
        zip -r release.zip . -x "*.git*" ".github/*"

    - name: Create Release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: "Release ${{ github.ref_name }}"  # Use the commit SHA as the tag
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          release.zip


   
    
