# This is a basic workflow to help you get started with Actions
name: Create Release on Push

on:

  push:
      
  workflow_dispatch:
   inputs:
      draft-release:
        type: boolean
        default: true
        description: Whether to publish the release as a draft.

permissions:
  packages: write
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Zip Project Files
      run: |
        zip -r release.zip . -x "*.git*" ".github/*"

    - name: Create Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "Release${{ github.sha }}"  # Use the commit SHA as the tag

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release.zip
